### ISSUE TITLE
History Account : ใส่ icon product / broker /account type และแสดงเลขบัญชีที่ใช้ ซื้อ 

### ISSUE THREAD

**Issue by tarro55** [canabit-developer/canabit_frontend#178]
![image](https://user-images.githubusercontent.com/33993571/159858955-ae1c7bd1-cfdb-476b-a6bc-03ec759ffe8b.png)

**Comment by paikung12** [comment]
/api/finance/accounttype/ เอารูปออกมาให้หน่อยครับ
