### ISSUE TITLE
การแสดงผลหน้า Register แสดง Text !ฟิลด์นี้จำเป็น แต่ไม่รู้ฟิลด์ไหนสำคัญในการ Register

### ISSUE THREAD

**Issue by LangTest001** [canabit-developer/canabit_frontend#53]
[http://localhost:3000/canabit_frontend/auth/register](url)
ต้องระบุด้วยว่าฟิลด์ไหนจำเป็น ต้องกรอกข้อมูลเพื่อทำการ Register อย่างถูกต้อง
![บัค1](https://user-images.githubusercontent.com/98881317/158538700-2eeb73e9-ad8d-4e4a-a2f4-46021663058a.jpg)

**Comment by tarro55** [comment]
มุแฮม
